package com.abhishek.urlshortener.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * JPA entity representing a mapping between a short URL code and the original
 * long URL.
 * Persisted in the {@code url_mapping} table.
 */
@Entity
@Table(name = "url_mapping")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class UrlMapping {

    /** Primary key; auto-generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The original long URL that was shortened. */
    @Column(name = "original_url", nullable = false, length = 2048)
    private String originalUrl;

    /** Unique short code or path used in the short URL (e.g. "abc12"). */
    @Column(name = "short_url", nullable = false, unique = true, length = 32)
    private String shortUrl;

    /** When this mapping was created. */
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    /**
     * Optional expiry time; after this, the short URL may be treated as invalid.
     */
    @Column(name = "expires_at")
    private LocalDateTime expiresAt;

    /** Number of times the short URL has been used (redirect clicks). */
    @Column(name = "click_count", nullable = false)
    private long clickCount = 0;

    /** Whether this mapping is active and can be used for redirects. */
    @Column(name = "active", nullable = false)
    private boolean active = true;
}
